#!/usr/bin/bash

bspc monitor -d 1 2 3 4 5 

bspc config border_width        2
bspc config window_gap          5

bspc config focus_follows_pointer true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a URxvt state=floating
bspc rule -a URxvt:calcurse state=floating
bspc rule -a URxvt:cmus state=floating
bspc rule -a Spotify state=floating
bspc rule -a mpv:gl state=floating
bspc rule -a Zathura state=tiled
bspc rule -a PacketTracer state=floating
bspc rule -a "VirtualBox Manager" state=floating
bspc rule -a "*" follow=off

wmname LG3D &

killall picom 
picom --backend glx --config ~/.config/picom/picom.conf -b &
killall polybar 
polybar example -c ~/.config/polybar/config &
redshift -c ~/.config/redshift/redshift.conf & 
